apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: istio-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: operations
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.12.2
    chart: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true

