apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prometheus-persistent-volume-chain.yaml
  - ./grafana-persistent-volume-chain.yaml
  - ./prometheus-deployment.yaml
  - ./grafana-deployment.yaml