apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: prometheus-deployment
  spec:
    replicas: 1
    selector:
      matchLabels: 
        tier: monitor
    template:
      metadata:
        labels:
          tier: monitor
      spec:
        containers:
        - name: prometheus
          image: prom/prometheus

          ports:
          - containerPort: 9090

          volumeMounts:
          - name: prometheus-volume
            mountPath: /data

       volumes:
       - name: prometheus-volume
         persistentVolumeClaim:
           claimName: pvc-prometheus