apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo
spec:
  generators:
  - git:
      repoURL: https://github.com/istio/istio.git
      revision: HEAD
      directories:
      - path: samples/bookinfo/platform/kube/bookinfo.yaml
      - path: samples/bookinfo/networking/bookinfo.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: operations
      source:
        repoURL: https://github.com/istio/istio.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true