apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app1-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - app1.prod
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app1-virtual-service
spec:
  hosts:
  - app1.prod
  gateways:
    - app1-gateway
  http:
    - match:
      - uri:
        prefix: /
    - route:
        - destination:
            host: production.app1.svc.cluster.local
            port:
              number: 80