apiVersion: v1
kind: ConfigMap
metadata:
  name: zero-proxy-appsetting
data:
  appsettings.json: |-
    {
      "Logging": 
      {
        "LogLevel": 
        {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "ReverseProxy": {
        "Routes": {
          "route1": {
            "ClusterId": "uibranding",
            "Match": {
              "Path": "/uibranding/{**remainder}"
            },
            "Transforms": [
              { "PathPattern": "/{**remainder}" }
            ]
          },
          "route2": {
            "ClusterId": "application1",
            "Match": {
              "Path": "/api/application1/{**remainder}"
            },
            "Transforms": [
              { "PathPattern": "/api/application1/{**remainder}" }
            ]
          },
          "route3": {
            "ClusterId": "application1",
            "Match": {
              "Path": "/application1/{**remainder}"
            },
            "Transforms": [
              { "PathPattern": "/{**remainder}" }
            ]
          },
          "routeDefault": {
            "ClusterId": "uishell",
            "Match": {
              "Path": "{**catch-all}"
            }
          }
        },
        "Clusters": {
          "application1": {
            "Destinations": {
              "destination1": {
                "Address": "http://development.app1/"
              }
            }
          },
          "uibranding": {
            "Destinations": {
              "destination1": {
                "Address": "http://localhost:8080/"
              }
            }
          },
          "uishell": {
            "Destinations": {
              "destination1": {
                "Address": "http://localhost:80/"
              }
            }
          }
        }
      }
    }