apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: configmap-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: Aplication1Address
  objref:
    kind: ConfigMap
    name: demo-configmap-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.Aplication1Address
configurations:
- params.yaml 
